/** Declaration file generated by dts-gen */

export = sheetrock;

declare function sheetrock(...args: any[]): any;

declare namespace sheetrock {
    const defaults: {
        callback: any;
        fetchSize: number;
        labels: any[];
        query: string;
        reset: boolean;
        rowTemplate: any;
        target: any;
        url: string;
    };

    const version: string;

}

